version: '3'

services:
  backend:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api-server:/app
      - ./data/public:/usr/app/public
    environment:
      NODE_ENV: production  # Set your desired environment variables here

  frontend:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongodb:
      image: "mongo:5.0.0-focal"
      container_name: "rantify_mongodb"
      ports:
          - "27077:27017"
      restart: always
      volumes:
          - "./data/mongodb:/data/db"
      environment:
          MONGO_INITDB_DATABASE: admin